server:
  port: 9595

application:
  no-fluff-jobs-client:
    base-url: https://nofluffjobs.com
    job-details-url: '${application.no-fluff-jobs-client.base-url}/pl/job/'
    response-max-size: 16777216
  cache:
    offersList:
      time-to-live: 1M
    offersDetails:
      time-to-live: 1H